### Решите задачи, выбирайте коллекции оптимально

Решение каждой задачи должно быть обоснованным, ожидаю:
- код
- краткое описание решения
- анализ сложности
- несколько тестовых кейсов (придумайте самостоятельно), будь въедливым, придумай неочевидные кейсы


In [1]:
from collections import defaultdict, deque
import itertools
import numpy as np
import pandas as pd
import cProfile

#### Задача 1.
На вход дается массив целых чисел nums и целое число target, верните индексы двух
чисел из nums так, чтобы их сумма равнялась target.
- Подумайте как использовать тут hash-таблицу или коллекцию основанную на хэш таблице
- Пример 1:
    - вход : nums = [2,7,11,15], target = 9
    - выход: [0, 1]



    

In [2]:
def two_sum(nums: list, target: int) -> list:
    kol_dict = defaultdict(set)
    for i, value in enumerate(nums):
        if (target - value) in kol_dict:
            # нечитаемый код, не могу понять что тут происходит - Adel исправила
            if len(kol_dict[target - value]) == 1:
              return [*kol_dict[target - value], i]
            else:
              return [*kol_dict[target - value]]
        kol_dict[value].add(i)
    return []

# не удачное задание входных данных, не понятно какой массив к какому таргету относиться - Adel исправила
nums_test_cases = (([2, 7, 11, 15], 9),
                    ([3, 5, 4, 6, 9], 9),
                    ([4, 4], 8),
                    ([2, 5, 3, 0], 5))
exp_result = ([0, 1], [1, 2], [0, 1], [0, 2])
for i in range(len(nums_test_cases)):
    print(two_sum(*nums_test_cases[i]))
    assert two_sum(*nums_test_cases[i]) == exp_result[i]
print(cProfile.run("two_sum([2,7,11,15], 9)"))

[0, 1]
[1, 2]
[0, 1]
[0, 2]
         6 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 3798928020.py:1(two_sum)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0.000 {method 'add' of 'set' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}


None


In [3]:
%%timeit
two_sum([2,7,11,15], 9)

909 ns ± 13 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


**Описание решения**: Для удобства запоминания позиций и самих элементов был выбран словарь defaultdict с возможностью вносить несколько значений (во избежание коллизий). Если число (target - текущий элемент) содержится в словаре, то выводим ответ, иначе добавляем значение в словарь. Если не нашлось подходящих элементов - выводим пустой список.

**Анализ сложности**: O(n) - наличие поэлементного цикла, O(1) - вставка значений в словарь ->  O(n) * O(1) = **O(n)** - алгоритмическая сложность. Скорее всего это самый оптимальный подход к решению задачи.

#### Задача 2.
Дан массив nums, содержащий n различных чисел в диапазоне [0, n], верните единственное число в этом диапазоне, отсутствующее в массиве.
- Подумайте как использовать тут hash-таблицу или коллекцию основанную на хэш таблице
- Пример 1:
    - вход: [3,0,1]
    - выход: 2

In [4]:
def number_absence(nums: list) -> int:
    num_set = set(nums)
    n = len(num_set)
    for i in range(n + 1):
        if i not in num_set:
            return i
    return -1

nums_test_cases = ([3, 0, 1], [9,6,4,2,3,5,7,0,1], [0, 1], [1, 2, 3, 4])
exp_result = (2, 8, 2, 0)
for i in range(len(nums_test_cases)):
    print(number_absence(nums_test_cases[i]))
    assert number_absence(nums_test_cases[i]) == exp_result[i]

2
8
2
0


In [5]:
%%timeit
number_absence([9,6,4,2,3,5,7,0,1])

601 ns ± 1.67 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


**Описание решения**: Чтобы работать только с уникальными значениями, было выбрано использование множества(set). Итерируемся от 0 до длины полученного множества, а также проверяем наличие текущего числа в коллекции. Если нашли число, которого нет - возрвращаем его, иначе - -1

**Анализ сложности**: O(n) - наличие поэлементного цикла ->  **O(n)** - алгоритмическая сложность.

##### Более легкий вариант без использования коллекций, но с такой же алгоритмической сложностью

In [6]:
def search_number(nums: list) -> int:
    n = len(nums)
    exp_sum = n * (n + 1) // 2
    actual_sum = sum(nums)
    return exp_sum - actual_sum

nums_test_cases = ([3, 0, 1], [9,6,4,2,3,5,7,0,1], [0, 1], [1, 2, 3, 4])
exp_result = (2, 8, 2, 0)
for i in range(len(nums_test_cases)):
    print(search_number(nums_test_cases[i]))
    assert search_number(nums_test_cases[i]) == exp_result[i]

2
8
2
0


In [7]:
%%timeit
search_number([9,6,4,2,3,5,7,0,1])

232 ns ± 6.37 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### Задача 3.
Дана строка s, найдите в ней первый неповторяющийся символ и верните его индекс.
Если он не существует, верните -1.
 - подумай как использовать очередь
 - Пример 1:
    - вход: "code"
    - выход: 0

In [8]:
def first_unique_char(s: str) -> int:
    queue = deque()
    count = defaultdict(int)
    for i in s:
        count[i] += 1
        queue.append(i)
    while queue:
        char = queue[0]
        if count[char] == 1:
            return s.index(char)
        else:
            queue.popleft()
    return -1

s_test_cases = ("code", "papa", "daddy", "helloworld")
exp_result = (0, -1, 1, 0)
for i in range(len(s_test_cases)):
    print(first_unique_char(s_test_cases[i]))
    assert first_unique_char(s_test_cases[i]) == exp_result[i]

0
-1
1
0


In [9]:
%%timeit
first_unique_char("code")

1.24 μs ± 36.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


**Описание решения**: По условиям задачи необходимо использовать очередь (deque из collections). Сначала заполняем очередь и словарь; затем проходимся по каждому элементу очереди. Если нашли индекс первого уникального символа - возрвращаем его, иначе удаляем элемент из очереди. Если индекс не нашелся - выводим -1.

**Анализ сложности**: O(n) - наличие поэлементного цикла,  O(n) - наличие цикла с условием,  O(1) - удаление элемента из очереди -> O(n) * O(n) * O(1) = **O(n^2)** - алгоритмическая сложность. (не эффективно)

##### Более легкий вариант без использования очереди, с алгоритмической сложностью **O(n)**

In [10]:
def f_unique_char(s: str) -> int:
    lst = list(dict.fromkeys(s))
    for letter in lst:
        if s.count(letter) == 1:
            return s.index(letter)
    return -1

s_test_cases = ("code", "papa", "daddy", "helloworld")
exp_result = (0, -1, 1, 0)
for i in range(len(s_test_cases)):
    print(f_unique_char(s_test_cases[i]))
    assert f_unique_char(s_test_cases[i]) == exp_result[i]

0
-1
1
0


In [11]:
%%timeit
f_unique_char("code")

718 ns ± 7.13 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### Задача 4.
Дана судоку 9 x 9. Она частично или полностью заполнена цифрами 1-9. Необходимо проверить следующие условия Каждая строка должна содержать цифры 1-9 без повторений.
Каждый столбец содержать цифры 1-9 без повторений.
Каждая из девяти подъячеек сетки 3 x 3 должна содержать цифры 1-9 без повторений. Если заполнение корректно вернуть true, если нет - false
- используйте numpy array
- Пример 1:
    - вход:
        - [[5,3,.,.,7,.,.,.,.]
        - ,[6,.,.,1,9,5,.,.,.]
        - ,[.,9,8,.,.,.,.,6,.]
        - ,[8,.,.,.,6,.,.,.,3]
        - ,[4,.,.,8,.,3,.,.,1]
        - ,[7,.,.,.,2,.,.,.,6]
        - ,[.,6,.,.,.,.,2,8,.]
        - ,[.,.,.,4,1,9,.,.,5]
        - ,[.,.,.,.,8,.,.,7,9]]
     - выход: true

In [17]:
def has_repeat(nums) -> bool:
    check = set()
    for i in nums:
        if i != "." and i in check:
            return True
        check.add(i)
    return False


def is_valid(array: list) -> bool:
    for row in array:
        if has_repeat(row):
            return False

    for col in range(9):
        column = [array[i][col] for i in range(9)]
        if has_repeat(column):
            return False

    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            square = [
                array[row][col]
                for row in range(i, i+3)
                for col in range(j, j+3)
            ]
            if has_repeat(square):
                return False
    return True

array_test_cases = ([
  [5, 3, ".", ".", 7, ".", ".", ".", "."],
  [6, ".", ".", 1, 9, 5, ".", ".", "."],
  [".", 9, 8, ".", ".", ".", ".", 6, "."],
  [8, ".", ".", ".", 6, ".", ".", ".", 3],
  [4, ".", ".", 8, ".", 3, ".", ".", 1],
  [7, ".", ".", ".", 2, ".", ".", ".", 6],
  [".", 6, ".", ".", ".", ".", 2, 8, "."],
  [".", ".", ".", 4, 1, 9, ".", ".", 5],
  [".", ".", ".", ".", 8, ".", ".", 7, 9]
],
[  [5, 3, ".", ".", 7, ".", ".", ".", "."],
  [6, ".", ".", 1, 9, 5, ".", ".", "."],
  [".", 9, 8, ".", ".", ".", ".", 6, "."],
  [8, ".", ".", ".", 6, ".", ".", ".", 3],
  [4, ".", 1, 8, ".", 3, ".", ".", 1],
  [7, ".", ".", ".", 2, ".", ".", ".", 6],
  [".", 6, ".", ".", ".", ".", 2, 8, "."],
  [".", ".", ".", 4, 1, 9, ".", ".", 5],
  [".", ".", ".", ".", 8, ".", ".", 7, 9]
])
exp_result = (True, False)
for i in range(len(array_test_cases)):
    print(is_valid(array_test_cases[i]))
    assert is_valid(array_test_cases[i]) == exp_result[i]

True
False


In [16]:
%%timeit
is_valid(array_test_cases[0])

25.5 μs ± 100 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


**Описание решения**: Добавлена вспомогательная функция для проверки подколлекции на наличие неуникальноых элементов. Проходимся по каждой строке и столбцу,  а также по каждой подъячейке 3х3. Если ни одна из проверок не срабатывает (все элементы являюся уникальными в подколлекциях), то выводится True - судоку валидна. Иначе False - заполнение некорректно  

**Анализ сложности**: O(n) - наличие поэлементного цикла -> O(n) * O(n)  = **O(n^2)** - алгоритмическая сложность.

##### С использованием массива numpy (и заменой точек на нули) - алгоритмическая сложность - **O(n^2)** - при размере судоку [n x n]

In [18]:
def has_repeat(nums) -> bool:
    without_zero = nums[nums != 0]
    return len(without_zero) != len(set(without_zero))


def is_valid_sudoku(array: np.ndarray) -> bool:
    for row in array:
        if has_repeat(row):
            return False

    for col in array.T:
        if has_repeat(col):
            return False

    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            square = array[i:i+3, j:j+3]
            if has_repeat(square):
                return False
    return True

array_test_cases = ( np.array([
  [5, 3, 0, 0, 7, 0, 0, 0, 0],
  [6, 0, 0, 1, 9, 5, 0, 0, 0],
  [0, 9, 8, 0, 0, 0, 0, 6, 0],
  [8, 0, 0, 0, 6, 0, 0, 0, 3],
  [4, 0, 0, 8, 0, 3, 0, 0, 1],
  [7, 0, 0, 0, 2, 0, 0, 0, 6],
  [0, 6, 0, 0, 0, 0, 2, 8, 0],
  [0, 0, 0, 4, 1, 9, 0, 0, 5],
  [0, 0, 0, 0, 8, 0, 0, 7, 9]
]),
np.array([
  [5, 3, 0, 0, 7, 0, 0, 0, 0],
  [6, 0, 0, 1, 9, 5, 0, 0, 0],
  [0, 9, 8, 0, 0, 0, 0, 6, 0],
  [8, 0, 0, 0, 6, 0, 0, 0, 3],
  [4, 0, 0, 4, 0, 3, 0, 0, 1],
  [7, 0, 0, 0, 2, 0, 0, 0, 6],
  [0, 6, 0, 0, 0, 0, 2, 8, 0],
  [0, 0, 0, 4, 1, 9, 0, 0, 5],
  [0, 0, 0, 0, 8, 0, 0, 7, 9]
]))

exp_result = (True, False)
for i in range(len(array_test_cases)):
    print(is_valid_sudoku(array_test_cases[i]))
    assert is_valid_sudoku(array_test_cases[i]) == exp_result[i]

True
False


In [19]:
%%timeit
is_valid_sudoku(array_test_cases[0])

92.5 μs ± 3.3 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


#### Задача 5.
Дан массив nums из различных целых чисел, верните все возможные перестановки в любом порядке.
- используйте numpy array
- реализуйте решение с использованием бибиотеки itertools и без нее
- Пример:
    - nums: [1,2,3]
    - выход: [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]
    

In [20]:
def permutation(nums: list) -> list:
    all_permutation = []
    for i in itertools.permutations(nums):
        all_permutation.append(list(i))
    return np.array(all_permutation)

nums_test_cases = ([1, 2, 3], [1, 2], [5], [5, 6, 7, 2])
for i in nums_test_cases:
    print(permutation(i))

[[1 2 3]
 [1 3 2]
 [2 1 3]
 [2 3 1]
 [3 1 2]
 [3 2 1]]
[[1 2]
 [2 1]]
[[5]]
[[5 6 7 2]
 [5 6 2 7]
 [5 7 6 2]
 [5 7 2 6]
 [5 2 6 7]
 [5 2 7 6]
 [6 5 7 2]
 [6 5 2 7]
 [6 7 5 2]
 [6 7 2 5]
 [6 2 5 7]
 [6 2 7 5]
 [7 5 6 2]
 [7 5 2 6]
 [7 6 5 2]
 [7 6 2 5]
 [7 2 5 6]
 [7 2 6 5]
 [2 5 6 7]
 [2 5 7 6]
 [2 6 5 7]
 [2 6 7 5]
 [2 7 5 6]
 [2 7 6 5]]


In [23]:
%%timeit
permutation(nums_test_cases[0])

3.49 μs ± 7.45 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
def permutation_without_itertools(nums: list) -> list:
    all_permutation = []

    def dfs(path, nums, all_permutation):
        if not nums:
            all_permutation.append(path)
        for i, value in enumerate(nums):
            dfs(path+[value], nums[:i]+nums[i+1:], all_permutation)
    dfs([], nums, all_permutation)
    return np.array(all_permutation)

for i in nums_test_cases:
    print(permutation_without_itertools(i))

[[1 2 3]
 [1 3 2]
 [2 1 3]
 [2 3 1]
 [3 1 2]
 [3 2 1]]
[[1 2]
 [2 1]]
[[5]]
[[5 6 7 2]
 [5 6 2 7]
 [5 7 6 2]
 [5 7 2 6]
 [5 2 6 7]
 [5 2 7 6]
 [6 5 7 2]
 [6 5 2 7]
 [6 7 5 2]
 [6 7 2 5]
 [6 2 5 7]
 [6 2 7 5]
 [7 5 6 2]
 [7 5 2 6]
 [7 6 5 2]
 [7 6 2 5]
 [7 2 5 6]
 [7 2 6 5]
 [2 5 6 7]
 [2 5 7 6]
 [2 6 5 7]
 [2 6 7 5]
 [2 7 5 6]
 [2 7 6 5]]


In [25]:
%%timeit
permutation_without_itertools(nums_test_cases[0])

10.1 μs ± 58.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


**Описание решения**: Реализован функционал метода itertools.permutations при помощи рекурсии

**Анализ сложности**: O(1) - добавление в словарь, O(n!) - наличие рекурсии  -> O(1) * O(n!)  = **O(n!)** - алгоритмическая сложность.

#### Задача 6.
Дан массив nums, найдите подмассив с наибольшей суммой и верните его сумму.
- Используй numpy array
- Пример 1:
    - вход: [-2,1,-3,4,-1,2,1,-5,4]
    - выход: [4,-1,2,1]

In [26]:
def max_sum_subarray(nums: list) -> int:
    max_sum = nums[0]
    current_sum = nums[0]
    for i in range(1, len(nums)):
        current_sum = max(nums[i], current_sum + nums[i])
        max_sum = max(current_sum, max_sum)
    return max_sum

nums_test_cases = ([-2, 1, -3, 4, -1, 2, 1, -5, 4], [3, 4, 11, 2, 7], [10, -5, 67, -2, -15, -51, -1, 0], [0, 0, 0, 0])
exp_result = (6, 27, 72, 0)
for i in range(len(nums_test_cases)):
    print(max_sum_subarray(nums_test_cases[i]))
    assert max_sum_subarray(nums_test_cases[i]) == exp_result[i]

6
27
72
0


In [27]:
%%timeit
max_sum_subarray(nums_test_cases[0])

2.21 μs ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [29]:
def max_subarray(nums: list) -> np.ndarray:
    current_sum = nums[0]
    max_sum = nums[0]
    current_subarray = [nums[0]]
    max_subarray = [nums[0]]
    for i in range(1, len(nums)):
        if current_sum + nums[i] > nums[i]:
            current_sum += nums[i]
            current_subarray.append(nums[i])
        else:
            current_sum = nums[i]
            current_subarray = [nums[i]]
        if current_sum > max_sum:
            max_sum = current_sum
            max_subarray = current_subarray.copy()
    return np.array(max_subarray)

exp_result = (np.array([4, -1, 2, 1]), np.array([3, 4, 11, 2, 7]), np.array([67]), np.array([0]))
for i in range(len(nums_test_cases)):
    print(max_subarray(nums_test_cases[i]))
    assert np.array_equal(max_subarray(nums_test_cases[i]), exp_result[i])

[ 4 -1  2  1]
[ 3  4 11  2  7]
[10 -5 67]
[0]


In [ ]:
%%timeit
max_subarray(nums_test_cases[0])

2.26 µs ± 472 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


**Описание решения**: В задании указано вернуть сумму. Для решения этой задачи воспользуемся алгоритмом Кадане для нахождение наибольшей суммы непрерывной подпоследовательности. Благодаря тому что используем две переменные и один поэлементный цикл - все интуитивно понятно. Если функция должна возвращать массив - все будет аналогично, с добавлением новых пееменных для хранения элементов непрерывной подпоследовательности.

**Анализ сложности**: O(n) - наличие поэлементного цикла  -> **O(n)** - алгоритмическая сложность.

#### Задача 7.
Дан массив интервалов intervals[i] = [start_i, end_i], объедините все пересекающиеся интервалы и верните массив непересекающихся интервалов, которые покрывают все интервалы на входе.
- Подумай как использовать сортировку
- Пример 1:
    - intervals: [[1,3],[2,6],[8,10],[15,18]]
    - выход: [[1,6],[8,10],[15,18]]

In [30]:
def merge(intervals: list) -> list:
    intervals.sort()
    result = [intervals[0]]
    for i in range(1, len(intervals)):
        start, end = intervals[i]
        last_interval = result[-1]
        last_end = last_interval[1]
        if start > last_end:
            result.append(intervals[i])
        else:
            last_interval[1] = max(last_end, end)
    return result

intervals_test_cases = ([[1, 3],[2, 6],[8, 10],[15, 18]], [[1, 2], [2, 3]], [[2, 6], [1, 4]])
exp_result = ([[1, 6],[8, 10],[15, 18]], [[1, 3]], [[1, 6]])
for i in range(len(intervals_test_cases)):
    print(merge(intervals_test_cases[i]))
    assert merge(intervals_test_cases[i]) == exp_result[i]

[[1, 6], [8, 10], [15, 18]]
[[1, 3]]
[[1, 6]]


In [31]:
%%timeit
merge(intervals_test_cases[0])

756 ns ± 12.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


**Описание решения**: Отсортируем интервалы для правильного решения. Пройдемся по каждому интервалу(элементу) в списке, сравнивая начало и конец интервалов. Выводим результат

**Анализ сложности**: O(n * log(n)) - сортировка интервалов, O(n) - наличие поэлементного цикла -> O(n * log(n)) + O(n) = **O(n * log(n))** - алгоритмическая сложность.

#### Задача 8.
Дан список неотрицательных целых чисел nums, расположите их так, чтобы они образовали наибольшее число, и верните его.
- Подумай как использовать сортировку
- Пример 1:
    - вход: [3,30,34,5,9]
    - выход: 9534330

In [32]:
def max_value(nums: list) -> int:
    nums_str = list(map(str, nums))
    n = len(nums_str)
    for i in range(n):
        for j in range(i + 1, n):
            if nums_str[i] + nums_str[j] < nums_str[j] + nums_str[i]:
                nums_str[i], nums_str[j] = nums_str[j], nums_str[i]

    result = "".join(nums_str)
    return int(result)

nums_test_cases = ([3, 30, 34, 5, 9], [1, 2], [5], [0, 6, 9, 291], [10, 2])
exp_result = (9534330, 21, 5, 962910, 210)
for i in range(len(nums_test_cases)):
    print(max_value(nums_test_cases[i]))
    assert max_value(nums_test_cases[i]) == exp_result[i]

9534330
21
5
962910
210


In [33]:
%%timeit
max_value(nums_test_cases[0])

3.35 μs ± 355 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


**Описание решения**: Изменяем тип элементов списка и сортировкой пузырьком приходим к верному решению.

**Анализ сложности**: O(n^2) - наличие алгоритма сортировки пузырьком -> **O(n^2)** - алгоритмическая сложность.

#### Задача 9.
Реализуй перемножение матриц "руками", используй numpy (@, mul, multiple)

In [35]:
a = np.array([[2, 5, 1, 6],
              [2, 4, 8, 1],
              [5, 7, 2, 0],
              [1, 4, 1, 3]])
b = np.array([[2, 5],
              [4, 1],
              [3, 1],
              [3, 0]])
c = np.array([[1, 8],
              [2, 3],
              [4, 4],
              [6, 7]])
d = np.array([[6, 1, 3, 7],
              [4, 0, 9, 2],
              [1, 2, 2, 0],
              [7, 5, 1, 3]])

matrices = {'a': a, 'b': b, 'c': c, 'd': d}

for i in itertools.product(itertools.combinations((a, b, c, d), 2), ("@", np.matmul, "*", np.multiply)):
    matrix1 = next(key for key, val in matrices.items() if np.array_equal(val, i[0][0]))
    matrix2 = next(key for key, val in matrices.items() if np.array_equal(val,i[0][1]))
    try:
        if i[1] in  ("@", "*"):
            result = eval(f"i[0][0] {i[1]} i[0][1]")
            print(f"Успешное перемножение {matrix1} и {matrix2}")
        else:
            result = i[1](i[0][0], i[0][1])
            print(f"Успешное перемножение {matrix1} и {matrix2}")
    except Exception as e:
        print(f"Для перемножения матриц {matrix1, matrix2} не подходит {i[1]}: {e}")


Успешное перемножение a и b
Успешное перемножение a и b
Для перемножения матриц ('a', 'b') не подходит *: operands could not be broadcast together with shapes (4,4) (4,2) 
Для перемножения матриц ('a', 'b') не подходит <ufunc 'multiply'>: operands could not be broadcast together with shapes (4,4) (4,2) 
Успешное перемножение a и c
Успешное перемножение a и c
Для перемножения матриц ('a', 'c') не подходит *: operands could not be broadcast together with shapes (4,4) (4,2) 
Для перемножения матриц ('a', 'c') не подходит <ufunc 'multiply'>: operands could not be broadcast together with shapes (4,4) (4,2) 
Успешное перемножение a и d
Успешное перемножение a и d
Успешное перемножение a и d
Успешное перемножение a и d
Для перемножения матриц ('b', 'c') не подходит @: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)
Для перемножения матриц ('b', 'c') не подходит <ufunc 'matmul'>: matmul: Input operand 1 h

In [36]:
def multiply_matrix(arr1: np.ndarray, arr2: np.ndarray) -> np.ndarray:
    if len(arr1[0]) != len(arr2):
        print("Количество столбцов первой матрицы не совпадает с количеством строк второй")
        return np.array([])
    result = [[0 for _ in range(len(arr2[0]))] for _ in range(len(arr1))]

    for i in range(len(arr1)):
        for j in range(len(arr2[0])):
            for k in range(len(arr2)):
                result[i][j] += arr1[i][k] * arr2[k][j]

    return np.array(result)

print(multiply_matrix(a, b))

[[45 16]
 [47 22]
 [44 34]
 [30 10]]


**Результат**: Перемножение матриц размером m*x*n и n*x*k возможно с помощью метода np.matmul() и операции @. Такие матрицы нельзя перемножить при помощи np.multiply() и операции \*. Однако они отлично справляются с перемножением матриц с одинаковой размерностью m*x*n и m*x*n. Матрицы одинаковой размерностью n*x*n можно перемножать любым способом.

#### Задача 10.
Датасет Титаник: https://www.kaggle.com/c/titanic/data

- A. Cоздать мультииндекс по Pclass и Sex, затем посчитать средний возраст.
- B. Найди максимальную стоимость билета (Fare) для каждой комбинации (Pclass, Embarked).
- С. Отсортировать пассажиров по возрасту (по убыванию), а при равном возрасте — по Fare (по возрастанию).
- D. Посчитать процент выживших в каждом классе (Pclass).
- E. Посчитать средний возраст и медианный тариф (Fare) для каждой комбинации (Pclass, Sex)
- F. Выберете всех женщин младше 30 лет, которые ехали в 1 классе.
- J. Посчитать скользящее среднее стоимости билета (Fare) по порядку PassengerId с окном 5.

#### A. Cоздать мультииндекс по Pclass и Sex, затем посчитать средний возраст.

In [39]:
titanic = pd.read_csv("data/train.csv")
df = pd.DataFrame(titanic)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [40]:
df_with_index = df.set_index(['Pclass', 'Sex'], inplace=False)
average_age = df_with_index.groupby(['Pclass', 'Sex'])['Age'].mean()
print(average_age)

Pclass  Sex   
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64


Если вместо пустых значений брать среднее

In [41]:
print(df["Age"].isna().sum())
avg_age = int(df["Age"].mean())
df["Age"] = df["Age"].replace(np.nan, avg_age)
print(df["Age"].isna().sum())
average_age = df.groupby(['Pclass', 'Sex'])['Age'].mean()
print(average_age)

177
0
Pclass  Sex   
1       female    34.074468
        male      39.167377
2       female    28.730263
        male      30.595648
3       female    23.864583
        male      27.182767
Name: Age, dtype: float64


#### B. Найди максимальную стоимость билета (Fare) для каждой комбинации (Pclass, Embarked).

In [42]:
max_fare = df.groupby(["Pclass", "Embarked"])["Fare"].max()
print(max_fare)

Pclass  Embarked
1       C           512.3292
        Q            90.0000
        S           263.0000
2       C            41.5792
        Q            12.3500
        S            73.5000
3       C            22.3583
        Q            29.1250
        S            69.5500
Name: Fare, dtype: float64


#### С. Отсортировать пассажиров по возрасту (по убыванию), а при равном возрасте — по Fare (по возрастанию).

In [43]:
sorted_df = df.sort_values(by=["Age", "Fare"],
                           ascending=[False, True])
print(sorted_df[["Name", "Age", "Fare"]])

                                     Name    Age     Fare
630  Barkworth, Mr. Algernon Henry Wilson  80.00  30.0000
851                   Svensson, Mr. Johan  74.00   7.7750
96              Goldschmidt, Mr. George B  71.00  34.6542
493               Artagaveytia, Mr. Ramon  71.00  49.5042
116                  Connors, Mr. Patrick  70.50   7.7500
..                                    ...    ...      ...
78          Caldwell, Master. Alden Gates   0.83  29.0000
469         Baclini, Miss. Helene Barbara   0.75  19.2583
644                Baclini, Miss. Eugenie   0.75  19.2583
755             Hamalainen, Master. Viljo   0.67  14.5000
803       Thomas, Master. Assad Alexander   0.42   8.5167

[891 rows x 3 columns]


#### D. Посчитать процент выживших в каждом классе (Pclass).

In [45]:
procent_survived = df.groupby("Pclass")["Survived"].value_counts(normalize=True) * 100
procent_survived_1 = procent_survived.xs(1, level="Survived")
print(procent_survived_1)

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: proportion, dtype: float64


#### E. Посчитать средний возраст и медианный тариф (Fare) для каждой комбинации (Pclass, Sex)

In [46]:
avg_age_and_median_fare = df.groupby(["Sex", "Pclass"]).agg({
    "Age": "mean",
    "Fare": "median"})
print(avg_age_and_median_fare)

                     Age      Fare
Sex    Pclass                     
female 1       34.074468  82.66455
       2       28.730263  22.00000
       3       23.864583  12.47500
male   1       39.167377  41.26250
       2       30.595648  13.00000
       3       27.182767   7.92500


#### F. Выберете всех женщин младше 30 лет, которые ехали в 1 классе.

In [47]:
women_younger_30 = df[(df["Sex"] == "female") & (df["Pclass"] == 1) & (df["Age"] < 30)]

print(women_younger_30["Name"])

31        Spencer, Mrs. William Augustus (Marie Eugenie)
88                            Fortune, Miss. Mabel Helen
136                         Newsom, Miss. Helen Monypeny
151                    Pears, Mrs. Thomas (Edith Wearne)
166               Chibnall, Mrs. (Edith Martha Bowerman)
256                       Thorne, Mrs. Gertrude Maybelle
290                         Barber, Miss. Ellen "Nellie"
291              Bishop, Mrs. Dickinson H (Helen Walton)
297                         Allison, Miss. Helen Loraine
306                              Fleming, Miss. Margaret
307    Penasco y Castellana, Mrs. Victor de Satode (M...
310                       Hays, Miss. Margaret Bechstein
311                           Ryerson, Miss. Emily Borie
329                         Hippach, Miss. Jean Gertrude
334    Frauenthal, Mrs. Henry William (Clara Heinshei...
341                       Fortune, Miss. Alice Elizabeth
356                          Bowerman, Miss. Elsie Edith
369                        Auba

#### J. Посчитать скользящее среднее стоимости билета (Fare) по порядку PassengerId с окном 5.

In [48]:
df = df.sort_values("PassengerId")
df["Avg_price"] = df["Fare"].rolling(window=5).mean()
print(df[["PassengerId", "Fare", "Avg_price"]])

     PassengerId     Fare  Avg_price
0              1   7.2500        NaN
1              2  71.2833        NaN
2              3   7.9250        NaN
3              4  53.1000        NaN
4              5   8.0500   29.52166
..           ...      ...        ...
886          887  13.0000   14.03834
887          888  30.0000   17.93500
888          889  23.4500   20.52500
889          890  30.0000   25.11500
890          891   7.7500   20.84000

[891 rows x 3 columns]
